export const GET_REQUEST_TO_USER_PROFILE = "GET_REQUEST_TO_USER_PROFILE";

export const GET_REQUEST_TO_PRODUCTS = "GET_REQUEST_TO_PRODUCTS";
export const GET_REQUEST_TO_PRODUCT = "GET_REQUEST_TO_PRODUCT";



