# Generated by Django 5.0.2 on 2024-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resetToken',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resetTokenEpiration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
