# Generated by Django 5.0.2 on 2024-02-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_resettoken_user_resettokenepiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='resetTokenEpiration',
            new_name='resetTokenExpiration',
        ),
    ]
