# Generated by Django 5.0.2 on 2024-03-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/user-default-image.png', null=True, upload_to='images'),
        ),
    ]
